### ISSUE TITLE
cannot download file random_idxes.txt

### ISSUE THREAD

**Issue by lyjgo** [speechbrain/benchmarks#12]
line 51 in /benchmarks/benchmarks/CL_MASR/common_voice_perpare.py throws an error:
_Downloading https://www.dropbox.com/s/v07nprnob0fugoy/random_idxes.txt?dl=1 to /workspace/project/benchmarks/benchmarks/CL_MASR/random_idxes.txt
random_idxes.txt?dl=1: 0.00B [00:02, ?B/s]
Traceback (most recent call last):
  File "train_agem.py", line 29, in <module>
    from common_voice_prepare import prepare_common_voice
  File "/workspace/project/benchmarks/benchmarks/CL_MASR/whisper/common_voice_prepare.py", line 51, in <module>
    download_file(_RANDOM_IDXES_URL, _RANDOM_IDXES_PATH)
  File "/opt/conda/lib/python3.8/site-packages/speechbrain/utils/data_utils.py", line 343, in download_file
    urllib.request.urlretrieve(
  File "/opt/conda/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/conda/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/conda/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
(base) root@d1311427135d:/workspace/project/benchmarks/benchmarks/CL_MASR/whisper# wget https://www.dropbox.com/s/v07nprnob0fugoy/random_idxes.txt?dl=1
--2023-11-24 16:28:25--  https://www.dropbox.com/s/v07nprnob0fugoy/random_idxes.txt?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.11.18
Connecting to www.dropbox.com (www.dropbox.com)|162.125.11.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/v07nprnob0fugoy/random_idxes.txt [following]
--2023-11-24 16:28:28--  https://www.dropbox.com/s/dl/v07nprnob0fugoy/random_idxes.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2023-11-24 16:28:28 ERROR 404: Not Found._

Since the file 'random_idxes.txt' looks important to the project, I wonder where can I download it.thanks

**Comment by lucadellalib** [comment]
I opened a pull request that should fix the issue (https://github.com/speechbrain/benchmarks/pull/13).

**Comment by mravanelli** [comment]
The fix is merged. Please @lyjgo, let us know if you experience other issues.

**Comment by lyjgo** [comment]
> The fix is merged. Please @lyjgo, let us know if you experience other issues.

thanks
