### ISSUE TITLE
cannot download file random_idxes.txt

### ISSUE THREAD

**Issue by 11abcdefghij11** [speechbrain/benchmarks#43]
Dear,i also met this problem ,how can i solve it? The followings are the details.
/ysl/code/CL/CLMASR/benchmarks/CL_MASR/wavlm/common_voice_prepare.py:35: UserWarning: torchaudio._backend.get_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  if torchaudio.get_audio_backend() != "sox_io":
/ysl/code/CL/CLMASR/benchmarks/CL_MASR/wavlm/common_voice_prepare.py:36: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("sox_io")
Downloading https://www.dropbox.com/sh/vfxrb7z0p79vhqt/AABHTNviie2xobwMOHfpPdy_a/random_idxes.txt?dl=1 to /newdisk0630/ysl/code/CL/CLMASR/benchmarks/CL_MASR/wavlm/random_idxes.txt
random_idxes.txt?dl=1: 0.00B [04:21, ?B/s]
Traceback (most recent call last):
  File "/anaconda3/envs/ysl_masr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "anaconda3/envs/ysl_masr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "anaconda3/envs/ysl_masr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "anaconda3/envs/ysl_masr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "anaconda3/envs/ysl_masr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "anaconda3/envs/ysl_masr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "anaconda3/envs/ysl_masr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "anaconda3/envs/ysl_masr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "anaconda3/envs/ysl_masr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "anaconda3/envs/ysl_masr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "train_ft.py", line 27, in <module>
    from common_voice_prepare import prepare_common_voice
  File "/ysl/code/CL/CLMASR/benchmarks/CL_MASR/wavlm/common_voice_prepare.py", line 52, in <module>
    download_file(_RANDOM_IDXES_URL, _RANDOM_IDXES_PATH)
  File "ysl/code/CL/CLMASR/speechbrain/speechbrain/utils/data_utils.py", line 346, in download_file
    urllib.request.urlretrieve(
  File "anaconda3/envs/ysl_masr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "anaconda3/envs/ysl_masr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "anaconda3/envs/ysl_masr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "anaconda3/envs/ysl_masr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "anaconda3/envs/ysl_masr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "anaconda3/envs/ysl_masr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "anaconda3/envs/ysl_masr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by 11abcdefghij11** [comment]
I tried to download the file directly through the link and successfully downloaded the random_idxes.txt, but when I tried to access the link of the tokenizer.zip, it says "You don't have access,You can ask the person who shared the link to invite you directly. "What should I do to solve it?
